### ISSUE TITLE
Omit qt / qt5 while compiling?

### ISSUE THREAD

**Issue by rubyFeedback** [flatpak/libportal#94] opened 2022-05-30 15:10 UTC
Hey guys,

I am trying to compile libportal right now.

It tells me this though:

"qmake found: NO need ['>= 5', '< 6']"
"Run-time dependency qt5 (modules: Core, Gui, Widgets, X11Extras) found: NO (tried pkgconfig and config-tool)"

I tried to compile qt5 with the kde dev patchsets, but had a problem with wayland so I gave up for now.

I need libportal for nautilus and evince eventually. Is there a flag to skip building qt? If there is, would
it be possible to mention it in the main README briefly? Perhaps a new entry right in the existing
"Passing options" would suffice. I am not that familiar with meson and I am not sure how the equivalent
to "./configure --help" goes with meson. Thanks for reading either way.

PS: Indepedent of this, perhaps qt5 should not be a fail-error but just a warning. I believe libportal
can work fine without qt but for some reason it aborts right now since I have no qt installed. I think
the better default would be to continue building, UNLESS qt is mandatory for libportal.

**Comment by rubyFeedback** [comment] 2022-05-30 15:35
I just compiled libportal-0.4 just fine, so it seems as if some option changed in this regard between 0.4 and 0.5 (and/or perhaps with meson). libportal-0.4. compiled fine here.

**Comment by eli-schwartz** [comment] 2022-05-30 21:21
> I am not that familiar with meson and I am not sure how the equivalent
> to "./configure --help" goes with meson.

I can confirm the equivalent. The command you are looking for is:

```
meson configure
```

**Comment by eli-schwartz** [comment] 2022-05-30 21:24
Looks like you have the following build option: `-Dbackends=gtk3,gtk4,qt5`

Whichever ones are added to that list are a fail-error.

Whichever ones are not in that option list, are not a warning -- they are simply not checked for and not built.

**Comment by eli-schwartz** [comment] 2022-05-30 21:26
From the README:

> After first running meson _build, you can view the available options with:
> ```
> meson configure _build
> ```

This is incorrect, the README should be fixed. You do NOT need to run `meson _build` before viewing the available options. Those instructions are for viewing *configured* options, not *available* ones.

**Closed** 2022-12-09 13:26 UTC
